#!/usr/bin/env python3
"""Regenerate every derived artefact in the repository from playbook frontmatter.

Playbook frontmatter is the single source of truth. This script rewrites:

* the coverage table in ``README.md``
* ``mappings/attack-coverage.md``
* ``mappings/attack-navigator-layer.json``
* ``mappings/legacy-technique-ids.md``
* ``validation/atomic-coverage.md``
* ``playbooks/README.md``
* the ``nav:`` section of ``mkdocs.yml``

CI runs ``--check``, which fails if any generated file is out of date. That makes
"the README says twenty playbooks but there are twenty-five" a build failure
rather than something a reader notices first.

Usage
-----
    python3 scripts/build.py            # regenerate
    python3 scripts/build.py --check    # fail if anything would change
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
PLAYBOOKS = ROOT / "playbooks"
MAPPINGS = ROOT / "mappings"
VALIDATION = ROOT / "validation"
ATTACK_SNAPSHOT = MAPPINGS / "attack-reference.json"
ATOMIC_SNAPSHOT = VALIDATION / "atomic-index.json"

BEGIN = "<!-- BEGIN GENERATED: {name} -->"
END = "<!-- END GENERATED: {name} -->"
BANNER = "<!-- Generated by scripts/build.py from playbook frontmatter. Do not edit by hand. -->"

TACTIC_ORDER = [
    "reconnaissance",
    "resource-development",
    "initial-access",
    "execution",
    "persistence",
    "privilege-escalation",
    "stealth",
    "defense-impairment",
    "credential-access",
    "discovery",
    "lateral-movement",
    "collection",
    "command-and-control",
    "exfiltration",
    "impact",
]


# --------------------------------------------------------------------------- #
# Loading
# --------------------------------------------------------------------------- #
def load_yaml(text: str) -> Any:
    try:
        import yaml  # noqa: PLC0415
    except ModuleNotFoundError:  # pragma: no cover - guidance path
        raise SystemExit("PyYAML is required: pip install -r requirements-dev.txt") from None
    return yaml.safe_load(text)


def parse_frontmatter(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise SystemExit(f"{path.name}: missing YAML frontmatter")
    _, frontmatter, body = text.split("---", 2)
    data = load_yaml(frontmatter)
    if not isinstance(data, dict):
        raise SystemExit(f"{path.name}: frontmatter is not a mapping")
    data["_path"] = path
    data["_body"] = body
    return data


def load_playbooks() -> list[dict[str, Any]]:
    playbooks = [parse_frontmatter(path) for path in sorted(PLAYBOOKS.glob("TH-*.md"))]
    return sorted(playbooks, key=lambda item: str(item["id"]))


def load_reference() -> dict[str, Any]:
    return json.loads(ATTACK_SNAPSHOT.read_text(encoding="utf-8"))


def load_atomics() -> dict[str, Any]:
    return json.loads(ATOMIC_SNAPSHOT.read_text(encoding="utf-8"))


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def technique_link(tid: str, reference: dict[str, Any]) -> str:
    info = reference["techniques"].get(tid)
    if not info:
        return f"`{tid}`"
    return f"[{tid}]({info['url']})"


def tactic_name(shortname: str, reference: dict[str, Any]) -> str:
    for value in reference["tactics"].values():
        if value["shortname"] == shortname:
            return value["name"]
    return shortname


def tactic_id(shortname: str, reference: dict[str, Any]) -> str:
    for key, value in reference["tactics"].items():
        if value["shortname"] == shortname:
            return key
    return ""


def replace_block(text: str, name: str, content: str) -> str:
    begin, end = BEGIN.format(name=name), END.format(name=name)
    if begin not in text or end not in text:
        raise SystemExit(f"missing generated-block markers for {name!r}")
    head = text.split(begin)[0]
    tail = text.split(end)[1]
    return f"{head}{begin}\n{BANNER}\n\n{content.rstrip()}\n\n{end}{tail}"


# --------------------------------------------------------------------------- #
# Renderers
# --------------------------------------------------------------------------- #
def render_readme_table(playbooks: list[dict[str, Any]], reference: dict[str, Any]) -> str:
    lines = [
        "| ID | Playbook | ATT&CK | Tactic | Severity | Status | KQL | Sigma | Tests |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for item in playbooks:
        attack = item["attack"]
        techniques = ", ".join(technique_link(tid, reference) for tid in attack["techniques"])
        tactic = tactic_name(attack["primary_tactic"], reference)
        path = item["_path"].name
        surfaces = item["surfaces"]
        lines.append(
            f"| {item['id']} | [{item['title']}](playbooks/{path}) | {techniques} | {tactic} | "
            f"{item['severity']} | {item['status']} | [query]({surfaces['kql']}) | "
            f"[rule]({surfaces['sigma']}) | [cases]({surfaces['tests']}) |"
        )
    return "\n".join(lines)


def render_readme_stats(
    playbooks: list[dict[str, Any]], reference: dict[str, Any], sigma_docs: int, test_cases: int
) -> str:
    techniques = sorted({tid for item in playbooks for tid in item["attack"]["techniques"]})
    tactics = sorted({item["attack"]["primary_tactic"] for item in playbooks})
    platforms = sorted({p for item in playbooks for p in item.get("platforms", [])})
    atomics = sorted({guid for item in playbooks for guid in (item.get("validation", {}) or {}).get("atomics", []) or []})
    strategies = sorted({d for item in playbooks for d in item["attack"].get("detection_strategies", [])})
    return "\n".join(
        [
            f"- **{len(playbooks)} playbooks** covering **{len(techniques)} ATT&CK techniques** "
            f"across **{len(tactics)} tactics** and {len(platforms)} platform families.",
            f"- **{len(playbooks)} KQL hunts** and **{sigma_docs} Sigma rule documents** "
            f"(detection rules plus correlation rules).",
            f"- **{test_cases} unit-test cases** asserting true-positive and false-positive behaviour "
            "for every Sigma rule, executed in CI.",
            f"- **{len(strategies)} ATT&CK Detection Strategies** (DET IDs) referenced, pinned to "
            f"Enterprise ATT&CK v{reference['attack_version']}.",
            f"- **{len(atomics)} Atomic Red Team tests** mapped by GUID and verified against the "
            "upstream index.",
        ]
    )


def render_coverage_matrix(
    playbooks: list[dict[str, Any]], reference: dict[str, Any], atomics: dict[str, Any]
) -> str:
    lines = [
        "# ATT&CK coverage matrix",
        "",
        BANNER,
        "",
        f"Enterprise ATT&CK **v{reference['attack_version']}** "
        f"(collection modified {reference['collection_modified'][:10]}).",
        "",
        "Coverage means a playbook exists with a hypothesis, telemetry requirements, at least one "
        "query surface, and unit tests. It does not mean the technique is fully detected: every "
        "playbook documents its own blind spots.",
        "",
        "## By tactic",
        "",
    ]

    by_tactic: dict[str, list[dict[str, Any]]] = {}
    for item in playbooks:
        by_tactic.setdefault(item["attack"]["primary_tactic"], []).append(item)

    for shortname in TACTIC_ORDER:
        entries = by_tactic.get(shortname)
        if not entries:
            continue
        lines.append(f"### {tactic_name(shortname, reference)} ({tactic_id(shortname, reference)})")
        lines.append("")
        lines.append("| ID | Playbook | Techniques | Detection strategies | Status |")
        lines.append("|---|---|---|---|---|")
        for item in entries:
            attack = item["attack"]
            techniques = ", ".join(technique_link(tid, reference) for tid in attack["techniques"])
            strategies = ", ".join(
                f"[{det}](https://attack.mitre.org/detectionstrategies/{det})"
                for det in attack.get("detection_strategies", [])
            ) or "—"
            lines.append(
                f"| {item['id']} | [{item['title']}](../playbooks/{item['_path'].name}) | "
                f"{techniques} | {strategies} | {item['status']} |"
            )
        lines.append("")

    lines += [
        "## Technique index",
        "",
        "| Technique | Name | Tactics | Playbooks | Atomic tests available |",
        "|---|---|---|---|---|",
    ]
    technique_to_playbooks: dict[str, list[str]] = {}
    for item in playbooks:
        for tid in item["attack"]["techniques"]:
            technique_to_playbooks.setdefault(tid, []).append(str(item["id"]))
    for tid in sorted(technique_to_playbooks):
        info = reference["techniques"].get(tid, {})
        tactics = ", ".join(info.get("tactic_names") or [])
        count = len(atomics.get("techniques", {}).get(tid, {}))
        lines.append(
            f"| {technique_link(tid, reference)} | {info.get('name', '?')} | {tactics} | "
            f"{', '.join(technique_to_playbooks[tid])} | {count if count else 'none published'} |"
        )

    lines += [
        "",
        "## Platform coverage",
        "",
        "| Platform | Playbooks |",
        "|---|---|",
    ]
    by_platform: dict[str, list[str]] = {}
    for item in playbooks:
        for platform in item.get("platforms", []):
            by_platform.setdefault(platform, []).append(str(item["id"]))
    for platform in sorted(by_platform):
        lines.append(f"| {platform} | {', '.join(by_platform[platform])} |")

    lines += [
        "",
        "## Deliberate gaps",
        "",
        "The library does not claim coverage of Reconnaissance, Resource Development, Initial Access "
        "or Exfiltration as tactics. Those either occur outside the estate's telemetry (Reconnaissance, "
        "Resource Development), are better served by control-specific tooling (Initial Access: mail "
        "security, vulnerability management), or are addressed indirectly through the collection and "
        "staging that precedes them (TH-019) and the channels used to carry them (TH-008, TH-016). "
        "Stating this explicitly is more useful than a matrix that implies uniform coverage.",
    ]
    return "\n".join(lines) + "\n"


def render_navigator_layer(playbooks: list[dict[str, Any]], reference: dict[str, Any]) -> str:
    severity_scores = {"critical": 100, "high": 80, "medium": 60, "low": 40, "informational": 20}
    techniques: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for item in playbooks:
        attack = item["attack"]
        score = severity_scores.get(str(item["severity"]).lower(), 50)
        for tid in attack["techniques"]:
            info = reference["techniques"].get(tid, {})
            for shortname in info.get("tactic_shortnames", []) or [attack["primary_tactic"]]:
                key = (tid, shortname)
                if key in seen:
                    continue
                seen.add(key)
                techniques.append(
                    {
                        "techniqueID": tid,
                        "tactic": shortname,
                        "score": score,
                        "color": "",
                        "comment": f"{item['id']} — {item['title']} ({item['status']})",
                        "enabled": True,
                        "metadata": [
                            {"name": "playbook", "value": str(item["id"])},
                            {"name": "severity", "value": str(item["severity"])},
                            {"name": "status", "value": str(item["status"])},
                        ],
                        "links": [],
                        "showSubtechniques": False,
                    }
                )
    layer = {
        "name": "ATT&CK Threat Hunting Playbook Library",
        "versions": {"attack": str(reference["attack_version"]).split(".")[0], "navigator": "5.1.0", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": (
            "Coverage of the ATT&CK Threat Hunting Playbook Library. Score reflects the playbook's "
            "declared severity, not detection confidence. Generated by scripts/build.py."
        ),
        "filters": {"platforms": ["Windows", "Linux", "macOS", "Azure AD", "Office 365", "SaaS", "IaaS", "Network"]},
        "sorting": 0,
        "layout": {"layout": "side", "showID": True, "showName": True},
        "hideDisabled": False,
        "techniques": sorted(techniques, key=lambda entry: (entry["techniqueID"], entry["tactic"])),
        "gradient": {"colors": ["#ffe766", "#ff6666"], "minValue": 0, "maxValue": 100},
        "legendItems": [
            {"label": "critical", "color": "#ff6666"},
            {"label": "high", "color": "#ff9966"},
            {"label": "medium", "color": "#ffe766"},
        ],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }
    return json.dumps(layer, indent=2) + "\n"


def render_legacy_ids(reference: dict[str, Any], playbooks: list[dict[str, Any]]) -> str:
    used = {tid for item in playbooks for tid in item["attack"]["techniques"]}
    revoked = reference["revoked_techniques"]
    relevant = {old: data for old, data in revoked.items() if data["replacement"] in used}
    lines = [
        "# Legacy technique IDs",
        "",
        BANNER,
        "",
        f"Enterprise ATT&CK **v{reference['attack_version']}** revoked {len(revoked)} technique IDs. "
        "Detection content written against older ATT&CK versions still carries the old IDs in its "
        "tags, and search engines still index them, so this table exists to make migration "
        "mechanical rather than archaeological.",
        "",
        "## IDs relevant to this library",
        "",
        "These revoked IDs map to techniques this library covers. If your existing rules are tagged "
        "with the legacy ID, they describe the same behaviour as the playbook listed.",
        "",
        "| Legacy ID | Legacy name | Current ID | Current name | Playbooks |",
        "|---|---|---|---|---|",
    ]
    technique_to_playbooks: dict[str, list[str]] = {}
    for item in playbooks:
        for tid in item["attack"]["techniques"]:
            technique_to_playbooks.setdefault(tid, []).append(str(item["id"]))
    for old in sorted(relevant):
        data = relevant[old]
        new = data["replacement"]
        lines.append(
            f"| `{old}` | {data['old_name']} | {technique_link(new, reference)} | "
            f"{data['replacement_name']} | {', '.join(technique_to_playbooks.get(new, []))} |"
        )

    lines += [
        "",
        "## Tactic restructure",
        "",
        "ATT&CK v19 replaced the single Defense Evasion tactic with two:",
        "",
        "| Current tactic | ID | Covers |",
        "|---|---|---|",
        "| Stealth | TA0005 | Blending in and avoiding observation (proxy execution, obfuscation, masquerading) |",
        "| Defense Impairment | TA0112 | Degrading the defences themselves (disabling tools, clearing logs) |",
        "",
        "Content tagged `attack.defense-evasion` is not wrong, only outdated: map it to whichever of "
        "the two tactics matches the behaviour it detects.",
        "",
        "## Full revoked-ID table",
        "",
        f"All {len(revoked)} revoked Enterprise technique IDs in v{reference['attack_version']}, for "
        "migrating content beyond this library's scope.",
        "",
        "| Legacy ID | Legacy name | Current ID | Current name |",
        "|---|---|---|---|",
    ]
    for old in sorted(revoked):
        data = revoked[old]
        lines.append(
            f"| `{old}` | {data['old_name']} | `{data['replacement']}` | {data['replacement_name']} |"
        )
    return "\n".join(lines) + "\n"


def render_atomic_coverage(playbooks: list[dict[str, Any]], atomics: dict[str, Any]) -> str:
    guid_lookup: dict[str, tuple[str, dict[str, Any]]] = {}
    for tid, tests in atomics.get("techniques", {}).items():
        for guid, data in tests.items():
            guid_lookup[guid] = (tid, data)

    lines = [
        "# Atomic Red Team validation coverage",
        "",
        BANNER,
        "",
        "Every test referenced here is verified in CI against "
        "[`validation/atomic-index.json`](atomic-index.json), a pinned snapshot of the upstream "
        "Atomic Red Team index. A GUID that no longer exists upstream fails the build, so this table "
        "cannot drift into fiction.",
        "",
        "Run these only in a lab or an approved test window, and record results in the hunt log.",
        "",
        "| Playbook | Technique | Atomic GUID | Test name | Platforms |",
        "|---|---|---|---|---|",
    ]
    uncovered: list[str] = []
    for item in playbooks:
        guids = (item.get("validation", {}) or {}).get("atomics") or []
        if not guids:
            uncovered.append(f"{item['id']} — {item['title']}")
            continue
        for guid in guids:
            tid, data = guid_lookup.get(guid, ("?", {}))
            lines.append(
                f"| {item['id']} | {tid} | `{guid}` | {data.get('name', 'unknown')} | "
                f"{', '.join(data.get('platforms', []))} |"
            )

    if uncovered:
        lines += [
            "",
            "## Playbooks with no published atomic tests",
            "",
            "Atomic Red Team publishes no tests for these techniques. Each playbook documents a "
            "manual validation procedure instead — an honest gap is more useful than a fabricated "
            "GUID.",
            "",
        ]
        lines += [f"- {entry}" for entry in uncovered]

    techniques_without = atomics.get("techniques_without_atomics") or []
    if techniques_without:
        lines += [
            "",
            "## Techniques with no atomics upstream",
            "",
            ", ".join(f"`{tid}`" for tid in techniques_without),
        ]
    return "\n".join(lines) + "\n"


def render_playbook_index(playbooks: list[dict[str, Any]], reference: dict[str, Any]) -> str:
    lines = [
        "# Playbook index",
        "",
        BANNER,
        "",
        "Each playbook is a self-contained hunt: hypothesis, telemetry prerequisites, analytic "
        "approach with tunable parameters, KQL and Sigma surfaces, unit tests, triage workflow, "
        "benign explanations, escalation criteria, purple-team validation, and documented blind "
        "spots.",
        "",
        "| ID | Playbook | Tactic | Severity | Confidence | Platforms |",
        "|---|---|---|---|---|---|",
    ]
    for item in playbooks:
        lines.append(
            f"| {item['id']} | [{item['title']}]({item['_path'].name}) | "
            f"{tactic_name(item['attack']['primary_tactic'], reference)} | {item['severity']} | "
            f"{item['confidence']} | {', '.join(item.get('platforms', []))} |"
        )
    lines += [
        "",
        "## Status meanings",
        "",
        "| Status | Meaning |",
        "|---|---|",
        "| `hunt` | Run periodically and review results by hand. Precision is not yet good enough to alert on. |",
        "| `production-candidate` | Ready to become a scheduled rule after local baselining and tuning. |",
        "| `production` | Deployed as an alert with an owner, thresholds set from local data, and a review cadence. |",
        "",
        "No content in this repository ships as `production`: that status can only be earned in a "
        "specific environment, against its own baseline.",
    ]
    return "\n".join(lines) + "\n"


def render_mkdocs_nav(playbooks: list[dict[str, Any]]) -> str:
    """Nav paths mirror the repository layout so every relative link works in both places."""
    lines = [
        "nav:",
        "  - Home: index.md",
        "  - Documentation home: docs/index.md",
        "  - Getting started:",
        "      - Deployment: docs/DEPLOYMENT.md",
        "      - Telemetry requirements: docs/TELEMETRY.md",
        "      - Data model: docs/DATA_MODEL.md",
        "      - Lab setup: docs/LAB.md",
        "  - Playbooks:",
        "      - Index: playbooks/README.md",
    ]
    for item in playbooks:
        lines.append(f"      - {item['id']} {item['title']}: playbooks/{item['_path'].name}")
    lines += [
        "  - Detection engineering:",
        "      - Testing and the Sigma engine: docs/TESTING.md",
        "      - Validation strategy: docs/VALIDATION.md",
        "      - Atomic Red Team validation: docs/ATOMIC_VALIDATION.md",
        "      - Tuning methodology: docs/TUNING.md",
        "      - Triage workflow: docs/TRIAGE.md",
        "      - Operating model: docs/OPERATING_MODEL.md",
        "      - Metrics: docs/METRICS.md",
        "  - Reference:",
        "      - ATT&CK coverage matrix: mappings/attack-coverage.md",
        "      - Detection strategies: docs/DETECTION_STRATEGIES.md",
        "      - Legacy technique IDs: mappings/legacy-technique-ids.md",
        "      - Atomic coverage: validation/atomic-coverage.md",
        "      - KQL style guide: docs/KQL_STYLE.md",
        "      - Sigma style guide: docs/SIGMA_STYLE.md",
        "      - Architecture: docs/ARCHITECTURE.md",
        "      - Design decisions: docs/DESIGN_DECISIONS.md",
        "      - Roadmap: docs/ROADMAP.md",
        "      - References: docs/REFERENCES.md",
        "  - Project:",
        "      - Portfolio walkthrough: docs/PORTFOLIO_WALKTHROUGH.md",
        "      - Publishing checklist: docs/GITHUB_PUBLISHING.md",
        "      - Contributing: CONTRIBUTING.md",
        "      - Security policy: SECURITY.md",
        "      - Disclaimer: DISCLAIMER.md",
        "      - Changelog: CHANGELOG.md",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Orchestration
# --------------------------------------------------------------------------- #
def count_sigma_documents() -> tuple[int, int]:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from sigma_eval import load_rule_file  # noqa: PLC0415

    docs = 0
    for path in sorted((ROOT / "rules" / "sigma").glob("TH-*.yml")):
        detections, correlations = load_rule_file(path)
        docs += len(detections) + len(correlations)

    cases = 0
    for path in sorted((ROOT / "tests" / "rules").glob("TH-*.yml")):
        fixture = load_yaml(path.read_text(encoding="utf-8"))
        cases += len(fixture.get("cases", []))
    return docs, cases


def build(check: bool) -> int:
    playbooks = load_playbooks()
    reference = load_reference()
    atomics = load_atomics()
    sigma_docs, test_cases = count_sigma_documents()

    outputs: dict[Path, str] = {}

    readme_path = ROOT / "README.md"
    readme = readme_path.read_text(encoding="utf-8")
    readme = replace_block(readme, "coverage-table", render_readme_table(playbooks, reference))
    readme = replace_block(
        readme, "stats", render_readme_stats(playbooks, reference, sigma_docs, test_cases)
    )
    outputs[readme_path] = readme

    mkdocs_path = ROOT / "mkdocs.yml"
    if mkdocs_path.exists():
        mkdocs = mkdocs_path.read_text(encoding="utf-8")
        begin, end = "# BEGIN GENERATED NAV", "# END GENERATED NAV"
        if begin in mkdocs and end in mkdocs:
            head = mkdocs.split(begin)[0]
            tail = mkdocs.split(end)[1]
            mkdocs = f"{head}{begin}\n{render_mkdocs_nav(playbooks)}\n{end}{tail}"
            outputs[mkdocs_path] = mkdocs

    outputs[MAPPINGS / "attack-coverage.md"] = render_coverage_matrix(playbooks, reference, atomics)
    outputs[MAPPINGS / "attack-navigator-layer.json"] = render_navigator_layer(playbooks, reference)
    outputs[MAPPINGS / "legacy-technique-ids.md"] = render_legacy_ids(reference, playbooks)
    outputs[VALIDATION / "atomic-coverage.md"] = render_atomic_coverage(playbooks, atomics)
    outputs[PLAYBOOKS / "README.md"] = render_playbook_index(playbooks, reference)

    stale: list[str] = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == content:
            continue
        if check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    if check:
        if stale:
            print("Generated files are out of date; run scripts/build.py:", file=sys.stderr)
            for name in stale:
                print(f" - {name}", file=sys.stderr)
            return 1
        print(f"Generated files are current ({len(outputs)} artefacts).")
        return 0

    print(
        f"Regenerated {len(outputs)} artefacts from {len(playbooks)} playbooks "
        f"({sigma_docs} Sigma documents, {test_cases} test cases)."
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if any generated file is stale")
    args = parser.parse_args()
    return build(args.check)


if __name__ == "__main__":
    sys.exit(main())
