#!/usr/bin/env python3
"""Generate the pinned Atomic Red Team index used for validation planning.

Every playbook proposes purple-team tests by Atomic Red Team GUID. Those GUIDs
are checked in CI against this snapshot so the repository can never reference a
test that does not exist, and so platform claims stay honest.

Source data: https://github.com/redcanaryco/atomic-red-team (``atomics/Indexes/index.yaml``)

Usage
-----
    python3 scripts/fetch_atomic_index.py                        # download and rebuild
    python3 scripts/fetch_atomic_index.py --index /tmp/index.yaml
    python3 scripts/fetch_atomic_index.py --check                # fail if the snapshot is stale

Only techniques referenced by the library are retained.
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "validation" / "atomic-index.json"
ATTACK_SNAPSHOT = ROOT / "mappings" / "attack-reference.json"
INDEX_URL = (
    "https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/"
    "atomics/Indexes/index.yaml"
)


def load_index(path: Path | None) -> dict[str, Any]:
    try:
        import yaml  # noqa: PLC0415
    except ModuleNotFoundError:  # pragma: no cover - guidance path
        raise SystemExit("PyYAML is required for this script: pip install pyyaml") from None
    if path is not None:
        return yaml.safe_load(path.read_text(encoding="utf-8"))
    print(f"Downloading {INDEX_URL} ...", file=sys.stderr)
    with urllib.request.urlopen(INDEX_URL, timeout=300) as response:  # noqa: S310
        return yaml.safe_load(response.read().decode("utf-8"))


def wanted_techniques() -> list[str]:
    reference = json.loads(ATTACK_SNAPSHOT.read_text(encoding="utf-8"))
    return sorted(reference["techniques"])


def build(index: dict[str, Any], technique_ids: list[str]) -> dict[str, Any]:
    collected: dict[str, dict[str, dict[str, Any]]] = {tid: {} for tid in technique_ids}
    for _tactic, techniques in (index or {}).items():
        for tid, body in (techniques or {}).items():
            if tid not in collected:
                continue
            for test in body.get("atomic_tests") or []:
                guid = test.get("auto_generated_guid")
                if not guid:
                    continue
                collected[tid][guid] = {
                    "name": test.get("name", "").strip(),
                    "platforms": sorted(test.get("supported_platforms") or []),
                    "elevation_required": bool(
                        (test.get("executor") or {}).get("elevation_required", False)
                    ),
                    "executor": (test.get("executor") or {}).get("name"),
                }
    return {
        "_comment": (
            "Generated by scripts/fetch_atomic_index.py from the Atomic Red Team index. "
            "Do not edit by hand. Atomic Red Team is (c) Red Canary, MIT licensed; see NOTICE.md."
        ),
        "source": INDEX_URL,
        "techniques": {
            tid: dict(sorted(tests.items())) for tid, tests in sorted(collected.items()) if tests
        },
        "techniques_without_atomics": [tid for tid, tests in sorted(collected.items()) if not tests],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--index", type=Path, help="path to a local Atomic Red Team index.yaml")
    parser.add_argument("--check", action="store_true", help="fail if the snapshot would change")
    args = parser.parse_args()

    snapshot = build(load_index(args.index), wanted_techniques())
    rendered = json.dumps(snapshot, indent=2, ensure_ascii=False) + "\n"

    if args.check:
        current = SNAPSHOT.read_text(encoding="utf-8") if SNAPSHOT.exists() else ""
        if current != rendered:
            print("Atomic index snapshot is stale; re-run scripts/fetch_atomic_index.py", file=sys.stderr)
            return 1
        print("Atomic index snapshot current")
        return 0

    SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT.write_text(rendered, encoding="utf-8")
    total = sum(len(tests) for tests in snapshot["techniques"].values())
    print(
        f"Wrote {SNAPSHOT.relative_to(ROOT)}: {len(snapshot['techniques'])} techniques, "
        f"{total} atomic tests, "
        f"{len(snapshot['techniques_without_atomics'])} techniques without atomics."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
